version: '3'

services:
  python_web_scrapping:
    image: python:latest
    container_name: python_web_scrapping
    volumes:
      - ./dependencies/requirements.txt:/requirements.txt  # Mounting requirements.txt
    command: sh -c "pip install -r /requirements.txt && python -m http.server"

