version: '3'

services:
  test:
    image: python:latest
    command: ["python", "-m", "http.server"]

version: '3'

services:
  python_web_scrapping:
    image: docker.io/library/python
    container_name: python_web_scrapping
    command: ["python", "-m", "http.server"]

