version: '3'

services:
  python_web_scrapping:
    image: python:latest
    container_name: python_web_scrapping
    volumes:
      - ./dependencies/py_lib_requirements.txt:/py_lib_requirements.txt  # Mounting py_lib_requirements.txt
    command: sh -c "apt update -y && apt install vim -y && pip install -r /py_lib_requirements.txt && git clone https://github.com/isudoajl/ml_supercross.git && python -m http.server"

